# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTokenInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=200)),
                ('scope', models.CharField(max_length=200)),
                ('expires_in', models.IntegerField()),
                ('user_id', models.CharField(max_length=200)),
                ('token_type', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
    ]
