# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-31 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_accesstokeninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstokeninfo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
